version: '3.8'

services:
  rancher:
    image: rancher/rancher:${APP_VERSION}
    container_name: ${APP_NAME}
    privileged: true
    ports:
      - ${APP_HTTP_PORT}:80
      - ${APP_HTTPS_PORT}:443
    restart: always
    command: --no-cacerts

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  rancher:
